[package]
name = "cock-roguelike-rework-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Remove "dynamic" after any releases or include libbevy_dylib
bevy = { version = "0.6.0", features = ["dynamic"] }
bevy_ascii_terminal = { version = "0.9.0" }
bevy_tiled_camera = { version = "0.3.0" }

#bevy_ecs_tilemap = { version = "0.5.0"}